ui = new window(global.game_uis.select, false);
ui.fit_to_gui();
chars = struct_get_names(Characters);
selected_char = "Amelia_Watson";
selected = 0;
char1o = 92;
char1yo = 70;
dbg = dbg_view("CharSelect", true, gui_x_percent(50));
dbg_section("Position");
create_view_from_instance(self);
mx = 0;
my = 0;
lmxx = 0;
lmy = 0;