display_set_gui_size(1280, 720);
instance_create_depth(x, y, depth, oCam);
GameData.selected_character = "Amelia_Watson";
char = GameData.characters[$ GameData.selected_character];
GameData.hp = char.hp;
GameData.max_hp = GameData.hp;
GameData.shield = 0;
GameData.max_shield = 0;
GameData.ATK = 0;
GameData.SPD = 0;
GameData.CRT = char.crit;
GameData.Pickup = 0;
GameData.Haste = 0;
//show_debug_overlay(true);
Player_Weapons[0] = variable_clone(Weapons[$ char.main_weapon]);
//Player_Weapons[0].level = 7;
//Player_Weapons[1] = variable_clone(Weapons[$ "BL_Book"]);
//Player_Weapons[1].level = 7;
image_xscale = 1;
image_yscale = 1;
depth = depth - 10;
inv_frame = 0;
movement = new topdown_movement(self, char.spd);
GameData.strafing = false;
GameData.arrow_dir = 0;
dir = 0;