sprite_index = wid.projectile_sprite;
c = method(self, wid.run_create);
bs = method(self, wid.run_begin_step);
s = method(self, wid.run_step);
es = method(self, wid.run_end_step);
d = method(self, wid.run_draw);
c();
hit_frame = 0;
hits = wid.hits[wid.level];
last_frame = frame + wid.duration;