sprite_index = wid.projectile_sprite;
c = method(self, wid.run_create);
bs = method(self, wid.run_begin_step);
s = method(self, wid.run_step);
es = method(self, wid.run_end_step);
d = method(self, wid.run_draw);
on_hit = method(self, wid.run_on_hit);
level = wid.level;
c();
hit_frame = 0;
hits = wid.hits[level];
last_frame = frame + wid.duration;