randomize();
down = false;
up = false;
edit_node = undefined;
node = undefined;
creating = false;

grid_template = {
  "width":1280.0,
  "name":"main_panel",
  "height":720.0,
  "top":50.0,

  "data":{
  },
  "nodes":[
    {
      "padding":0.0,
      "flexDirection":"row",
      "name":"top_panel_grid",
      "height":300.0,
      "flex":1.0,
      "top":0.0,
      "data":{
      },
      "nodes":[
        {
          "width":60.0,
          "name":"grid_panel1",
          "flex":1.0,
          "padding":0.0,
          "data":{
          },
			"nodes":[
				{
          "minHeight":160.0,
          "maxHeight":0.0,
          "padding":0.0,
          "maxWidth":0.0,
          "flex":1.0,
          "nodes":[
            {
              "padding":10.0,
              "width":90.0,
              "name":"portrait",
              "height":83.0,
              "top":0.0,
              "data":{
                "image":"sUiPortraitFrame"
              }
            },
            {
              "marginTop":89.0,
              "padding":0.0,
              "positionType":"absolute",
              "marginLeft":31.0,
              "width":58.0,
              "name":"special_timer",
              "height":18.0,
              "marginRight":0.0,
              "data":{
              }
            },
            {
              "minHeight":158.0,
              "maxHeight":158.0,
              "padding":0.0,
              "maxWidth":319.0,
              "flex":1.0,
              "nodes":[
                {
                  "name":"hpbar",
                  "height":17.0,
                  "padding":0.0,
                  "data":{
                  }
                },
                {
                  "padding":4.0,
                  "flex":1.0,
                  "nodes":[
                    {
                      "padding":0.0,
                      "flex":1.0,
                      "nodes":[
                        {
                          "name":"w0",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"w1",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "padding":10.0,
                          "flex":1.0,
                          "width":60.0,
                          "name":"w2",
                          "data":{
                          },
                          "flexDirection":"row"
                        },
                        {
                          "name":"w3",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"w4",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"w5",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        }
                      ],
                      "name":"weapons_panel",
                      "height":60.0,
                      "data":{
                      },
                      "flexDirection":"row"
                    },
                    {
                      "padding":0.0,
                      "flex":1.0,
                      "nodes":[
                        {
                          "name":"i0",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i1",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i2",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i3",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i4",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i5",
                          "padding":10.0,
                          "flex":1.0,
                          "data":{
                          },
                          "width":60.0
                        }
                      ],
                      "name":"items_panel",
                      "height":60.0,
                      "data":{
                      },
                      "flexDirection":"row"
                    }
                  ],
                  "height":60.0,
                  "margin":4.0,
                  "marginTop":13.0,
                  "marginBottom":8.0,
                  "name":"panel_72420",
                  "border":0.0,
                  "marginRight":0.0,
                  "data":{
                    "image":"sItemsArea"
                  }
                }
              ],
              "width":66.0,
              "height":160.0,
              "marginLeft":7.0,
              "name":"other_panel",
              "data":{
              },
              "minWidth":319.0
            },
            {
              "padding":10.0,
              "flex":1.0,
              "width":60.0,
              "name":"panel_34362",
              "height":60.0,
              "data":{
              }
            },
            {
              "padding":9.0,
              "nodes":[
                {
                  "marginTop":4.0,
                  "padding":0.0,
                  "marginBottom":4.0,
                  "marginLeft":14.0,
                  "width":64.0,
                  "name":"stage",
                  "height":12.0,
                  "data":{
                  }
                },
                {
                  "marginTop":2.0,
                  "padding":10.0,
                  "width":93.0,
                  "name":"time",
                  "height":24.0,
                  "data":{
                  }
                }
              ],
              "width":109.0,
              "name":"stage_panel",
              "height":60.0,
              "data":{
              }
            }
          ],
          "height":160.0,
          "flexDirection":"row",
          "marginTop":-13.0,
          "marginLeft":8.0,
          "name":"info_panel",
          "top":0.0,
          "data":{
          },
          "minWidth":727.0,
          "left":0.0
        },
			]
        },
        {
          "margin":0.0,
          "padding":0.0,
          "width":60.0,
          "name":"grid_panel2",
          "flex":1.0,
          "data":{
          }
        },
        {
          "width":60.0,
          "name":"grid_panel3",
          "flex":1.0,
          "padding":0.0,
          "data":{
          }
        }
      ],
      "left":0.0
    },
    {
      "padding":0.0,
      "flexDirection":"row",
      "name":"middle_panel_grid",
      "height":300.0,
      "flex":1.0,
      "top":0.0,
      "data":{
      },
      "nodes":[
        {
          "width":60.0,
          "name":"grid_panel4",
          "flex":1.0,
          "padding":0.0,
          "data":{
          }
        },
        {
          "margin":0.0,
          "padding":0.0,
          "border":0.0,
          "width":60.0,
          "name":"grid_panel5",
          "flex":1.0,
          "data":{
          }
        },
        {
          "flexBasis":0.0,
          "padding":0.0,
          "width":60.0,
          "name":"grid_panel6",
          "flex":1.0,
          "data":{
          }
        }
      ],
      "left":0.0
    },
    {
      "padding":0.0,
      "flexDirection":"row",
      "name":"bottom_panel_grid",
      "height":300.0,
      "flex":1.0,
      "top":0.0,
      "data":{
      },
      "nodes":[
        {
          "margin":0.0,
          "padding":0.0,
          "width":60.0,
          "name":"grid_panel7",
          "flex":1.0,
          "data":{
          }
        },
        {
          "width":60.0,
          "name":"grid_panel8",
          "flex":1.0,
          "padding":0.0,
          "data":{
          }
        },
        {
          "width":60.0,
          "name":"grid_panel9",
          "flex":1.0,
          "padding":0.0,
          "data":{
          }
        }
      ],
      "left":0.0
    }
  ],
  "left":275.0
}
clear_template = {
    "width":1280.0,
    "name":"main_panel",
    "height":720.0,
    "top":50.0,
    "data":{
    },
    "left":275.0
};
//template = global.game_uis.rooms;
template = grid_template;
//template = clear_template;
ui = new window(template, true);
ui.edit_mode();

new_window = function() {
	ui.dispose();
	ui = new window(template, true);
	ui.edit_mode();
}

clearstr = function(struct) {
	var names = struct_get_names(struct);
	if (array_contains(names, "instances")) {
	    struct_remove(struct, "instances");
	}
	if (struct_exists(struct.data, "owner")) {
	    struct_remove(struct.data, "owner");
	}
	if (struct_exists(struct.data, "inst")) {
	    struct_remove(struct.data, "inst");
	}	
	if (array_contains(names, "nodes")) {
	    array_foreach(struct.nodes, function(e, i) {
			clearstr(e);
		});
	}	
}

save = function(name = "test") {
	var f = file_text_open_write(name);
	var str = variable_clone(flexpanel_node_get_struct(ui.root));
	clearstr(str);
	file_text_write_string(f, json_stringify(str, true));
	file_text_close(f);
}

load = function() {
	ui.dispose();
	ui = new window(json_parse(buffer_read(buffer_load("/home/airgeadlamh/.config/DenoTest1/test.ui"), buffer_text)), true);
	//ui.edit_mode();
}

depth = depth + 1;