global.game_uis = {};
global.game_uis.stage = {
  "width":1280.0,
  "name":"base",
  "height":720.0,
  "nodes":[
    {
      "margin":0.0,
      "padding":0.0,
      "width":1366.0,
      "name":"panel_base",
      "flex":0.0,
      "height":720.0,
      "nodes":[
        {
          "padding":0.0,
          "maxHeight":41.0,
          "name":"xp",
          "flex":1.0,
          "height":71.0,
          "data":{
            "image":"sExpBarBG"
          }
        },
        {
          "flexDirection":"row",
          "padding":0.0,
          "minHeight":160.0,
          "maxHeight":0.0,
          "minWidth":727.0,
          "height":160.0,
          "marginTop":-13.0,
          "maxWidth":0.0,
          "name":"info_panel",
          "flex":1.0,
          "nodes":[
            {
              "padding":10.0,
              "width":90.0,
              "name":"portrait",
              "height":83.0,
              "top":0.0,
              "data":{
                "image":"sUiPortraitFrame"
              }
            },
            {
              "padding":0.0,
              "marginRight":0.0,
              "marginTop":89.0,
              "width":58.0,
              "name":"special_timer",
              "height":18.0,
              "data":{
              },
              "marginLeft":31.0,
              "positionType":"absolute"
            },
            {
              "padding":0.0,
              "minHeight":158.0,
              "maxHeight":158.0,
              "minWidth":319.0,
              "width":66.0,
              "height":160.0,
              "maxWidth":319.0,
              "flex":1.0,
              "name":"other_panel",
              "nodes":[
                {
                  "name":"hpbar",
                  "height":17.0,
                  "padding":0.0,
                  "data":{
                  }
                },
                {
                  "padding":4.0,
                  "height":60.0,
                  "margin":4.0,
                  "marginRight":0.0,
                  "marginTop":13.0,
                  "marginBottom":8.0,
                  "name":"panel_72420",
                  "flex":1.0,
                  "nodes":[
                    {
                      "flexDirection":"row",
                      "padding":0.0,
                      "name":"weapons_panel",
                      "flex":1.0,
                      "height":60.0,
                      "nodes":[
                        {
                          "name":"w0",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"w1",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "flexDirection":"row",
                          "padding":10.0,
                          "width":60.0,
                          "name":"w2",
                          "flex":1.0,
                          "data":{
                          }
                        },
                        {
                          "name":"w3",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"w4",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"w5",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        }
                      ],
                      "data":{
                      }
                    },
                    {
                      "flexDirection":"row",
                      "padding":0.0,
                      "name":"items_panel",
                      "flex":1.0,
                      "height":60.0,
                      "nodes":[
                        {
                          "name":"i0",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i1",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i2",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i3",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i4",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        },
                        {
                          "name":"i5",
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "width":60.0
                        }
                      ],
                      "data":{
                      }
                    }
                  ],
                  "data":{
                    "image":"sItemsArea"
                  },
                  "border":0.0
                }
              ],
              "data":{
              },
              "marginLeft":7.0
            },
            {
              "padding":10.0,
              "width":60.0,
              "name":"panel_34362",
              "flex":1.0,
              "height":60.0,
              "data":{
              }
            },
            {
              "padding":9.0,
              "width":109.0,
              "name":"stage_panel",
              "height":60.0,
              "nodes":[
                {
                  "padding":0.0,
                  "marginTop":4.0,
                  "marginBottom":4.0,
                  "width":64.0,
                  "name":"stage",
                  "height":12.0,
                  "data":{
                  },
                  "marginLeft":14.0
                },
                {
                  "padding":10.0,
                  "marginTop":2.0,
                  "width":93.0,
                  "name":"time",
                  "height":24.0,
                  "data":{
                  }
                }
              ],
              "data":{
              }
            }
          ],
          "top":0.0,
          "data":{
          },
          "marginLeft":8.0,
          "left":0.0
        },
        {
          "padding":10.0,
          "width":60.0,
          "name":"panel_8777",
          "flex":1.0,
          "height":60.0,
          "data":{
          }
        },
        {
          "name":"buffs",
          "height":60.0,
          "margin":10.0,
          "padding":10.0,
          "data":{
          }
        },
        {
          "padding":10.0,
          "width":60.0,
          "name":"panel_87397",
          "flex":0.33000001311302185,
          "height":60.0,
          "data":{
          }
        }
      ],
      "top":0.0,
      "data":{
        "image":"gamea"
      },
      "left":0.0
    }
  ],
  "top":50.0,
  "data":{
  },
  "left":275.0
}

global.game_uis.pause = {
  "data":{
    "image":"pauseda"
  },
  "nodes":[
    {
      "data":{
        "image":"sMenu"
      },
      "gapColumn":1.0,
      "padding":0.0,
      "nodes":[
        {
          "maxHeight":46.0,
          "marginTop":26.0,
          "marginBottom":18.0,
          "margin":0.0,
          "name":"paused",
          "marginLeft":54.0,
          "data":{
            "image":"sHudPaused"
          },
          "maxWidth":144.0,
          "flex":0.18000000715255737,
          "padding":10.0,
          "height":60.0
        },
        {
          "data":{
          },
          "flex":1.0,
          "padding":8.0,
          "nodes":[
            {
              "data":{
                "image":"sHudButton"
              },
              "maxHeight":43.0,
              "minWidth":140.0,
              "flex":1.0,
              "marginTop":6.0,
              "marginBottom":17.0,
              "width":60.0,
              "name":"button_character",
              "height":57.0
            },
            {
              "data":{
              },
              "maxHeight":43.0,
              "minWidth":140.0,
              "flex":1.0,
              "marginBottom":17.0,
              "width":60.0,
              "name":"button_stamps",
              "height":60.0
            },
            {
              "data":{
              },
              "maxHeight":43.0,
              "minWidth":140.0,
              "flex":1.0,
              "marginBottom":17.0,
              "width":60.0,
              "name":"button_collabs",
              "height":60.0
            },
            {
              "data":{
              },
              "maxHeight":43.0,
              "minWidth":140.0,
              "flex":1.0,
              "marginBottom":17.0,
              "width":60.0,
              "name":"button_resume",
              "height":60.0
            },
            {
              "data":{
              },
              "maxHeight":43.0,
              "minWidth":140.0,
              "flex":1.0,
              "marginBottom":17.0,
              "border":0.0,
              "width":60.0,
              "name":"button_settings",
              "height":60.0
            },
            {
              "data":{
              },
              "maxHeight":43.0,
              "minWidth":140.0,
              "flex":1.0,
              "marginBottom":35.0,
              "margin":0.0,
              "width":60.0,
              "name":"button_quit",
              "height":41.0
            }
          ],
          "alignSelf":"center",
          "name":"panel_49436",
          "height":60.0,
          "alignItems":"center"
        }
      ],
      "alignSelf":"center",
      "width":257.0,
      "name":"panel_base",
      "height":490.0,
      "left":0.0,
      "top":140.0
    }
  ],
  "width":1280.0,
  "name":"base",
  "height":720.0,
  "left":275.0,
  "top":50.0
}

global.game_uis.main_menu = {
  "nodes":[
    {
      "alignItems":"center",
      "padding":0.0,
      "flex":1.0,
      "nodes":[
        {
          "padding":10.0,
          "width":284.0,
          "name":"version",
          "height":40.0,
          "positionType":"absolute",
          "top":11.0,
          "data":{
          },
          "left":985.0
        },
        {
          "padding":10.0,
          "width":445.0,
          "name":"title",
          "marginTop":17.0,
          "height":199.0,
          "data":{
            "image":"spr_HoloCureTitle"
          }
        }
      ],
      "name":"chars",
      "height":300.0,
      "top":0.0,
      "data":{
      },
      "left":0.0
    },
    {
      "padding":0.0,
      "alignContent":"",
      "flex":0.25999999046325684,
      "nodes":[
        {
          "width":60.0,
          "name":"button_leaderboards",
          "height":60.0,
          "margin":0.0,
          "data":{
          },
          "left":-88.0
        },
        {
          "marginLeft":4.0,
          "width":60.0,
          "marginRight":0.0,
          "height":60.0,
          "name":"button_achievements",
          "margin":0.0,
          "data":{
          },
          "left":-52.0
        },
        {
          "marginLeft":0.0,
          "width":60.0,
          "marginRight":0.0,
          "height":60.0,
          "name":"button_shop",
          "margin":0.0,
          "data":{
          },
          "left":-12.0
        },
        {
          "marginLeft":0.0,
          "width":60.0,
          "name":"button_play",
          "height":60.0,
          "margin":0.0,
          "data":{
          },
          "left":25.0
        },
        {
          "width":60.0,
          "marginRight":0.0,
          "height":60.0,
          "name":"button_house",
          "margin":0.0,
          "data":{
          },
          "left":68.0
        },
        {
          "width":60.0,
          "name":"button_settings",
          "height":60.0,
          "margin":0.0,
          "data":{
          },
          "left":109.0
        },
        {
          "width":60.0,
          "name":"button_credits",
          "height":60.0,
          "margin":0.0,
          "data":{
          },
          "left":146.0
        },
        {
          "width":60.0,
          "name":"button_quit",
          "height":60.0,
          "margin":0.0,
          "data":{
          },
          "left":185.0
        }
      ],
      "height":300.0,
      "flexDirection":"row",
      "alignItems":"center",
      "name":"panel_btn",
      "alignSelf":"center",
      "justifyContent":"flex-end",
      "top":0.0,
      "data":{
        "image":"sTitleBar"
      },
      "left":0.0
    },
    {
      "padding":0.0,
      "flex":0.059999998658895493,
      "name":"bottom",
      "height":300.0,
      "top":0.0,
      "data":{
        "image":""
      },
      "left":0.0
    }
  ],
  "width":1280.0,
  "name":"base",
  "height":720.0,
  "justifyContent":"flex-end",
  "top":50.0,
  "data":{
    "image":"sTitleBG"
    //"image":"Menu"
  },
  "left":275.0
}

global.game_uis.character_stats = {
  "width":1280.0,
  "name":"base",
  "height":720.0,
  "nodes":[
    {
      "padding":0.0,
      "width":305.0,
      "name":"panel_base",
      "height":300.0,
      "nodes":[
        {
          "flexDirection":"row",
          "padding":6.0,
          "name":"back",
          "height":40.0,
          "nodes":[
            {
              "name":"panel_36812",
              "flex":0.25,
              "padding":10.0,
              "data":{
              },
              "width":60.0
            },
            {
              "name":"name",
              "flex":1.0,
              "padding":10.0,
              "data":{
              },
              "width":60.0
            }
          ],
          "data":{
          }
        },
        {
          "padding":5.0,
          "name":"panel_68356",
          "flex":1.0,
          "height":60.0,
          "nodes":[
            {
              "name":"HP",
              "flex":1.0,
              "height":60.0,
              "padding":10.0,
              "data":{
              }
            },
            {
              "name":"ATK",
              "flex":1.0,
              "height":60.0,
              "padding":10.0,
              "data":{
              }
            },
            {
              "name":"SPD",
              "flex":1.0,
              "height":60.0,
              "padding":10.0,
              "data":{
              }
            },
            {
              "name":"CRT",
              "flex":1.0,
              "height":60.0,
              "padding":10.0,
              "data":{
              }
            },
            {
              "name":"Pickup",
              "flex":1.0,
              "height":60.0,
              "padding":10.0,
              "data":{
              }
            },
            {
              "padding":10.0,
              "name":"Haste",
              "flex":1.0,
              "height":60.0,
              "marginBottom":0.0,
              "data":{
              }
            }
          ],
          "data":{
          }
        }
      ],
      "top":270.0,
      "data":{
      },
      "left":70.0
    }
  ],
  "top":50.0,
  "data":{
    "image":"pauseda"
  },
  "left":275.0
}