e = Enemies[$ name];
hp = e.hp;
atk = e.atk;
sprite_index = e.sprite;
speed = e.spd;
direction = point_direction(x, y, oPlayer.x, oPlayer.y);
image_xscale = e.scale;
image_yscale = e.scale;
ds_queue_enqueue(oGame.dir_queue, self.id);
was_hit = false;
inv_frame = 0;
attack_frame = 0;